### ISSUE TITLE
Support (non - video stream) camera image communication

### ISSUE THREAD

**Issue by moooeeeep** [dfki-ric/robot_remote_control#36]
We consider to add support for communicating data from a ROS `sensor_msgs/Image` or `sensor_msgs/CompressedImage` topic to a `base::samples::frame::Frame` type port.

I've had a quick look at the code. Would this be the relevant changes? 

* add a message type to this file: https://github.com/dfki-ric/robot_remote_control/blob/master/src/Types/RobotRemoteControl.proto
* Add conversions for ROS and Rock types here: https://github.com/dfki-ric/robot_remote_control/tree/master/src/Types/Conversions

Any other hints / remarks before we start with this?

**Comment by chhtz** [comment]
This is working (and tested) now. Some bugfixes are in the [add_image_conversions](https://github.com/dfki-ric/robot_remote_control/tree/add_image_conversions)-branch. Shall we make PRs to master or to devel now, @planthaber ?
