### ISSUE TITLE
Provide example (or fully-integrated support) for dispatching multiple telemetry/command inputs of the same type to a separate topic/port at the output side.

### ISSUE THREAD

**Issue by moooeeeep** [dfki-ric/robot_remote_control#41]
Currently RRC seems to support only one channel of data for each data type.

There is a short entry in the docs about this, which suggests that logic could be added to decide based on frame id to which topic or port to dispatch, or add a switch to reconfigure the one-to-one mapping programmatically: https://github.com/dfki-ric/robot_remote_control/blob/master/doc/FAQ.md#how-do-i-control-different-parts-using-twist-pose-or-goto

It would be great if there was an example for the required adjustments on the sides of the robot controller, as well as the controlled robot. 

If there is no fundamental opposition against it, one could maybe implement (and communicate) this notion of communication channel (or port name or topic name) for messages on the low level protocol, i.e., to prevent dropping messages of one channel, if the ring buffer gets drowned by another channel's data of the same message type. Also to enable this functionality for messages that don't have a header.

**Comment by planthaber** [comment]
> It would be great if there was an example for the required adjustments on the sides of the robot controller, as well as the controlled robot.

Just after you read the command, look at the frame and either (in case of e.G. ROS) write it to the one or the other publisher. Before sending the command, set the frame name. But true, there is no extra buffer for cases where the frequencies differ a lot between frames or "channels" on the same line. 

From a performance view I don't like to add another value in the "non-protobuf" part or the protocol, which currently only contains the messagy type. 

There is already a similar approach for the "SimpleSensor" vlaues, where each simple Sensor id gets its own buffer.

So one could create a new "ChannelMessage" protobuf type, that contains the message type id, and the channel id (i guess it should be an int then for faster cpp container access), and a protobuf::any type with the actual message. When the RingBuffer (e.g. TelemetryBuffer or CommandBuffer) does not exists, it is created.

But this way it would not be easily available through the normal interface, but mus specifically be selected to use another method to send/receive the data.

On the other hand, additional id (uint_8?) wouldn't hurt in the protocol, and dereferencing it to store the message in the buffer also won't, but it has to be checked on every message it the buffer exists.

**Comment by planthaber** [comment]
I started a test implementation for channel support (without breaking the original interface
)
https://github.com/dfki-ric/robot_remote_control/pull/43

**Comment by planthaber** [comment]
Accidentally create the PR for master, here is the correct one: https://github.com/dfki-ric/robot_remote_control/pull/44

**Comment by planthaber** [comment]
@moooeeeep There is now a (hopefully) working version of channel support on the "channels" branch, which you could try.

Only missing part is the question whether to give up the special SimpleSensor handling in favor of channels

**Comment by planthaber** [comment]
Channel branch merged
